### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by tsuberim** [daostack/migration#3]
commands in `package.json` require `rm -rf`, `mkdir`, `cat`, `jq`, replace them with the cross platform npm equivalent.

**Comment by dkent600** [comment]
#32 partially addresses the problems, but the docker commands still don't work.

**Comment by ben-kaufman** [comment]
This should be working now but I'm unable to test it as I don't have Windows, closing for now and please reopen if this is still relevant.

**Comment by dkent600** [comment]
Docker command still doesn't work.  This is in powershell where are least one has `cat`:

```
$ npm run docker:build

> @daostack/migration@0.0.1-rc.23-v2 docker:build C:\Users\dkent\Documents\Projects\GitHub\DAOStack\migration
> docker build . -t daostack/migration:$(cat package.json | jq -r '.version')

'jq' is not recognized as an internal or external command,
operable program or batch file.
```
